# Generated by Django 5.0.6 on 2024-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('image', models.ImageField(upload_to='assets/images/')),
                ('type', models.CharField(choices=[('Pic', 'Hình ảnh'), ('Rep', 'Bài viết'), ('Chef', 'Đầu bếp')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialEvent',
        ),
    ]
