# Generated by Django 5.0.6 on 2024-05-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_aboutus_delete_specialevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='type',
            field=models.CharField(choices=[('Pic', 'Hình ảnh'), ('Rep', 'Bài viết'), ('Sta', 'Nhân viên')], max_length=3),
        ),
    ]
