# Generated by Django 5.0.4 on 2024-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_date_alter_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
