# Generated by Django 5.0.4 on 2024-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
