# Generated by Django 5.0.4 on 2024-05-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_reservation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_activated',
        ),
    ]
