# Generated by Django 5.0.6 on 2024-05-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_activated',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('order_desc', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
