# Generated by Django 5.0.6 on 2024-05-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_reservation_is_activated_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
    ]
