# Generated by Django 5.0.6 on 2024-05-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
